# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict/predict.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15predict/predict.proto\x12\x07predict\"H\n\x14\x43reatePredictRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\x12\x10\n\x08sentence\x18\x02 \x01(\t\x12\x0e\n\x06intent\x18\x03 \x01(\t\"9\n\x15\x43reatePredictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x12GetPredictsRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x03\"E\n\x13GetPredictsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"3\n\x11GetPredictRequest\x12\x0e\n\x06itemID\x18\x01 \x01(\x03\x12\x0e\n\x06userID\x18\x02 \x01(\x03\"D\n\x12GetPredictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"D\n\x14UpdatePredictRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08sentence\x18\x02 \x01(\t\x12\x0e\n\x06intent\x18\x03 \x01(\t\"9\n\x15UpdatePredictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x14\x44\x65letePredictRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"9\n\x15\x44\x65letePredictResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9b\x03\n\x0ePredictService\x12P\n\rCreatePredict\x12\x1d.predict.CreatePredictRequest\x1a\x1e.predict.CreatePredictResponse\"\x00\x12J\n\x0bGetPredicts\x12\x1b.predict.GetPredictsRequest\x1a\x1c.predict.GetPredictsResponse\"\x00\x12G\n\nGetPredict\x12\x1a.predict.GetPredictRequest\x1a\x1b.predict.GetPredictResponse\"\x00\x12P\n\rUpdatePredict\x12\x1d.predict.UpdatePredictRequest\x1a\x1e.predict.UpdatePredictResponse\"\x00\x12P\n\rDeletePredict\x12\x1d.predict.DeletePredictRequest\x1a\x1e.predict.DeletePredictResponse\"\x00\x42\nZ\x08/predictb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict.predict_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010/predict'
  _CREATEPREDICTREQUEST._serialized_start=34
  _CREATEPREDICTREQUEST._serialized_end=106
  _CREATEPREDICTRESPONSE._serialized_start=108
  _CREATEPREDICTRESPONSE._serialized_end=165
  _GETPREDICTSREQUEST._serialized_start=167
  _GETPREDICTSREQUEST._serialized_end=203
  _GETPREDICTSRESPONSE._serialized_start=205
  _GETPREDICTSRESPONSE._serialized_end=274
  _GETPREDICTREQUEST._serialized_start=276
  _GETPREDICTREQUEST._serialized_end=327
  _GETPREDICTRESPONSE._serialized_start=329
  _GETPREDICTRESPONSE._serialized_end=397
  _UPDATEPREDICTREQUEST._serialized_start=399
  _UPDATEPREDICTREQUEST._serialized_end=467
  _UPDATEPREDICTRESPONSE._serialized_start=469
  _UPDATEPREDICTRESPONSE._serialized_end=526
  _DELETEPREDICTREQUEST._serialized_start=528
  _DELETEPREDICTREQUEST._serialized_end=562
  _DELETEPREDICTRESPONSE._serialized_start=564
  _DELETEPREDICTRESPONSE._serialized_end=621
  _PREDICTSERVICE._serialized_start=624
  _PREDICTSERVICE._serialized_end=1035
# @@protoc_insertion_point(module_scope)
