# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from predict import predict_pb2 as predict_dot_predict__pb2


class PredictServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePredict = channel.unary_unary(
                '/predict.PredictService/CreatePredict',
                request_serializer=predict_dot_predict__pb2.CreatePredictRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.CreatePredictResponse.FromString,
                )
        self.GetPredicts = channel.unary_unary(
                '/predict.PredictService/GetPredicts',
                request_serializer=predict_dot_predict__pb2.GetPredictsRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.GetPredictsResponse.FromString,
                )
        self.GetPredict = channel.unary_unary(
                '/predict.PredictService/GetPredict',
                request_serializer=predict_dot_predict__pb2.GetPredictRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.GetPredictResponse.FromString,
                )
        self.UpdatePredict = channel.unary_unary(
                '/predict.PredictService/UpdatePredict',
                request_serializer=predict_dot_predict__pb2.UpdatePredictRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.UpdatePredictResponse.FromString,
                )
        self.DeletePredict = channel.unary_unary(
                '/predict.PredictService/DeletePredict',
                request_serializer=predict_dot_predict__pb2.DeletePredictRequest.SerializeToString,
                response_deserializer=predict_dot_predict__pb2.DeletePredictResponse.FromString,
                )


class PredictServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredicts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePredict': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePredict,
                    request_deserializer=predict_dot_predict__pb2.CreatePredictRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.CreatePredictResponse.SerializeToString,
            ),
            'GetPredicts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredicts,
                    request_deserializer=predict_dot_predict__pb2.GetPredictsRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.GetPredictsResponse.SerializeToString,
            ),
            'GetPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredict,
                    request_deserializer=predict_dot_predict__pb2.GetPredictRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.GetPredictResponse.SerializeToString,
            ),
            'UpdatePredict': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePredict,
                    request_deserializer=predict_dot_predict__pb2.UpdatePredictRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.UpdatePredictResponse.SerializeToString,
            ),
            'DeletePredict': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePredict,
                    request_deserializer=predict_dot_predict__pb2.DeletePredictRequest.FromString,
                    response_serializer=predict_dot_predict__pb2.DeletePredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predict.PredictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predict.PredictService/CreatePredict',
            predict_dot_predict__pb2.CreatePredictRequest.SerializeToString,
            predict_dot_predict__pb2.CreatePredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPredicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predict.PredictService/GetPredicts',
            predict_dot_predict__pb2.GetPredictsRequest.SerializeToString,
            predict_dot_predict__pb2.GetPredictsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predict.PredictService/GetPredict',
            predict_dot_predict__pb2.GetPredictRequest.SerializeToString,
            predict_dot_predict__pb2.GetPredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predict.PredictService/UpdatePredict',
            predict_dot_predict__pb2.UpdatePredictRequest.SerializeToString,
            predict_dot_predict__pb2.UpdatePredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/predict.PredictService/DeletePredict',
            predict_dot_predict__pb2.DeletePredictRequest.SerializeToString,
            predict_dot_predict__pb2.DeletePredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
